language: node_js
cache: 
 directories:
  - ~/.npm
node_js: 
 - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true,
  cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  project_name: "MasterEats"
  target-branch: gh-pages
  commit_message: "Deploy Release from: %{git_branch} & with message: %{git_commit_msg}"
  verbose: true
  on:
    branch: development